[gsheets]
type = "service_account"
project_id = "streamlit-connect-406919"
private_key_id = "1f251b5092b2951e5cd23ad64cfa9123268ec94c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5/6pFcn52ZJi9
qRt6zPEelV9oFCemIkYp24W+qGHJ6To5gwDG1t2XnN0aQc4de0fiBqTzoa23nr5o
...RESTO DE LA CLAVE...
-----END PRIVATE KEY-----"""
client_email = "cyclistic-data@streamlit-connect-406919.iam.gserviceaccount.com"
client_id = "107980603043150053950"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/cyclistic-data%40streamlit-connect-406919.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[email]
gmail = "gcerato@gmail.com"
password = "jptb xrhh myyk enfy"
